adminUser:
  password: vault:jx-aps-killerdandy/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-killerdandy:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-killerdandy:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-killerdandy/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-killerdandy/prow:hmacToken
